<!DOCTYPE html>
<html lang="fr" ng-app="myTennisPal">
    <head>
        <meta charset="utf-8"/>
        <title>Mon partenaire - Accueil</title>

        <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css"/>
        <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css"/>
<!--        <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>-->

        <script type="application/javascript" src="/js/vendor/angular.min.js"></script>
        <script type="application/javascript" src="/js/vendor/angular-route.min.js"></script>
        <script type="application/javascript" src="/js/vendor/jquery.min.js"></script>
        <script type="application/javascript" src="/js/vendor/bootstrap.min.js"></script>
        <script type="application/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.17"></script>

        <script type="text/javascript" src="/js/src/ng/app.js"></script>
        <script type="text/javascript" src="/js/src/ng/controller/index.js"></script>
        <script type="text/javascript" src="/js/src/ng/factory/marker.js"></script>
        <script type="text/javascript" src="/js/src/ng/resource/scrapped_place_marker/mapper.js"></script>
        <script type="text/javascript" src="/js/src/ng/resource/place_marker/mapper.js"></script>
        <script type="text/javascript" src="/js/src/ng/service/navigator_geolocation.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Mon Partenaire</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="/">Accueil</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="content">
            <?php echo $this->getContent() ?>
        </div>
    </body>
</html>